export enum CodeSessionActionStatus {
    CREATE_SESSION_IN_PROGRESS = 'CREATE_SESSION_IN_PROGRESS',
    CREATE_SESSION_FAILED = 'CREATE_SESSION_FAILED',
    CREATE_SESSION_SUCCESSFUL = 'CREATE_SESSION_SUCCESSFUL',

    FETCH_CODE_SESSION_IN_PROGRESS = 'FETCH_CODE_SESSION_IN_PROGRESS',
    FETCH_CODE_SESSION_FAILED = 'FETCH_CODE_SESSION_FAILED',
    FETCH_CODE_SESSION_SUCCESSFUL = 'FETCH_CODE_SESSION_SUCCESSFUL',
}

enum CodeSessionActions {
    CREATE_SESSION = 'code-session/create-session',
    FETCH_CODE_SESSION = 'code-session/fetch-code-session',
}

export default CodeSessionActions