export enum AuthActionStatus {
    LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL',
    REGISTER_IN_PROGRESS = 'REGISTER_IN_PROGRESS',
    REGISTER_FAILED = 'REGISTER_FAILED',
    REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL',
    AUTHENTICATION_IN_PROGRESS = 'AUTHENTICATION_IN_PROGRESS',
    AUTHENTICATION_SUCCESSFUL = 'AUTHENTICATION_SUCCESSFUL',
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
}

enum AuthActions {
    LOGIN = 'auth/login',
    REGISTER = 'auth/register',
    GET_AUTH_USER = 'auth/get_auth_user',
}

export default AuthActions